apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexthouse-fe
  labels:
    app: nexthouse-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexthouse-fe
  template:
    metadata:
      labels:
        app: nexthouse-fe
    spec:
      containers:
      - name: test
        image: eastshine96/nexthouse-fe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: SERVLET_CONTEXT_PATH