apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexthouse_fe
  labels:
    app: nexthouse_fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexthouse_fe
  template:
    metadata:
      labels:
        app: nexthouse_fe
    spec:
      containers:
      - name: nexthouse_fe
        image: eastshine96/nexthouse_fe:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: nexthouse_fe-config
              key: SERVLET_CONTEXT_PATH